spree_customized/config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do

    get "mail_methods/email_users/send" => "mail_methods#email_users", as: :email_users
    post "mail_methods/post_email_users/send" => "mail_methods#post_email_users", as: :post_email_users
    resources :tenants
    resources :sliders
    resources :socials
    resources :promo_banners

    resources :users do
      get :send_email_notification
    end
    resources :donations, only: [:index]

    namespace :jne do
      resources :shippings do
        collection { post :upload }
        collection { get :collection_search_base}
      end
    end
    resources :menu, only: [:index, :create]
    resources :pages
    resources :product_reviews, only: [:index, :edit, :update, :destroy] do
      put :update_status
    end
    resources :states do
      resources :cities
    end

    resources :cities, only: [:index] do
      resources :sub_districts
    end

    resources :sub_districts, only: [:index]

    resources :products do
      collection { post :upload_file}
    end

    resources :taxons

    # resources :users do
    #   # collection do
    #   #   get :index_customer
    #   #   post :create_customer
    #   #   get :new_customer
    #   #   get 'edit_customer/:id/edit', :as => :edit_customer, :action => 'edit_customer'
    #   #   put 'update_customer/:id', :as => :update_customer, :action => 'update_customer'
    #   #   delete 'destroy_customer/:id', :as => :destroy_customer, :action => 'destroy_customer'
    #   # end
    # end

    resources :roles
    resources :features
    resources :home
    resources :users_customers
    resources :reports_customers
    resources :activity_logs do
      collection { get 'show_by_date/:date', :as => :show_by_date, :action => 'show_by_date'}
    end
  end

  resources :pages, only: [:show]
  resources :translations, only: [:show]

  namespace :api, defaults: { format: 'json' } do
  	resources :tenants
    resources :cities, only:[:index, :show]
    resources :sub_districts, only:[:index, :show]

    namespace :nontenant, defaults: { format: 'json' } do
      resources :products, only:[:index, :show]
      resources :users
      get "check_email_exist" => "users#check_email_exist", as: :check_user
      get "get_single_payment_method" => "general#get_single_payment_method", as: :get_single_payment_method
      get "get_single_shipping_method" => "general#get_single_shipping_method", as: :get_single_shipping_method
      get "get_single_shipping_rate" => "general#get_single_shipping_rate", as: :get_single_shipping_rate
      get "get_single_shipping_rate_by_tenant" => "general#get_single_shipping_rate_by_tenant", as: :get_single_shipping_rate_by_tenant
      post "custom_order" => "general#custom_order", as: :custom_order

      concern :order_routes do
        member do
          put :cancel
          put :empty
          put :apply_coupon_code
        end

        resources :line_items
        resources :payments do
          member do
            put :authorize
            put :capture
            put :purchase
            put :void
            put :credit
          end
        end

        resources :shipments, only: [:create, :update] do
          member do
            put :ready
            put :ship
            put :add
            put :remove
          end
        end

        resources :addresses, only: [:show, :update]

        resources :return_authorizations do
          member do
            put :add
            put :cancel
            put :receive
          end
        end
      end

      resources :checkouts, only: [:update], concerns: :order_routes do
        member do
          put :next
          put :advance
        end
      end
      get '/orders/mine', to: 'orders#mine', as: 'my_orders'
      get "/orders/current", to: "orders#current", as: "current_order"
      resources :orders, concerns: :order_routes
      resources :shipments, only: [:create, :update] do
        member do
          put :ready
          put :ship
          put :add
          put :remove
        end
      end
    end

    devise_for :spree_user,
               :class_name => 'Spree::User',
               :controllers => { :sessions => 'spree/api/user_sessions', :passwords => 'spree/api/user_passwords'},
               :skip => [:unlocks, :omniauth_callbacks, :registrations],
               :path_prefix => :api,
               :path => :user
  end

  post 'cart' => "orders#edit", as: :cart_path_post
  get "account/orders" => "users#orders", as: :account_orders
  get "account/addresses" => "users#addresses", as: :account_addresses
  get "account/configuration" => "users#configuration", as: :account_configuration

  resources :products do
    collection do
      get "categories/:category_name" => "products#index", as: :products_category
    end
  end

  devise_scope :spree_user do
    get '/confirmation/:token' => 'user_registrations#confirmation', :as => :confirmation
  end

  get "states_by_country" => "info_addresses#states_by_country", as: :states_by_country
  get "cities_by_country" => "info_addresses#cities_by_country", as: :cities_by_country
  get "cities_by_state" => "info_addresses#cities_by_state", as: :cities_by_state
  get "sub_districts_by_city" => "info_addresses#sub_districts_by_city", as: :sub_districts_by_city
  get "be-a-member/:package_type" => "users#be_a_member", as: :be_a_member
  get "be-a-member/completed/:transaction_no" => "users#be_a_member_completed", as: :be_a_member_completed
  post "submit_be_a_member" => "users#submit_be_a_member", as: :submit_be_a_member
  patch "submit_be_a_member" => "users#submit_be_a_member", as: :submit_be_a_member_update

  resources :product_reviews, only: [:create]
  resources :orders do
    collection do
      post :donation
    end
  end
  resources :donations, only: [:index, :create, :show]
end

spree_customized/app/models/spree/calculator/shipping/free_shipping.rb
require_dependency 'spree/shipping_calculator'

module Spree
  module Calculator::Shipping
    class FreeShipping < Calculator
      def self.description
        Spree.t(:free_shipping)
      end

      def compute(object)
        if object.is_a?(Array)
          return if object.empty?
          order = object.first.order
        else
          order = object
        end

        #order.ship_total
        0.0
      end
    end
  end
end

spree_customized/app/models/spree/calculator/shipping/per_item_decorator.rb
Spree::Calculator::Shipping::PerItem.class_eval do
  def compute_package(package)
    if calculable.use_jne?
      compute_package_jne(package, calculable.jne_type)      
    else
      content_items = package.contents
      self.preferred_amount * content_items.sum { |item| item.quantity }
    end
  end

  def compute_package_jne(package, type_package)
    jne_price = Spree::Jne::Shipping.get_price(package, type_package)
    price = jne_price ? jne_price : self.preferred_amount

    content_items  = package.contents
    total = 0
    content_items.each_with_index do |content_item, index|
      item   = content_item.variant if content_item.variant
      weight = item ? item.weight.to_f : 0.0
      width  = item ? item.width.to_f : 0.0
      height = item ? item.height.to_f : 0.0
      depth  = item ? item.depth.to_f : 0.0
      total += price * [weight, (width * height * depth / 6000)].max * content_item.quantity
    end
    total
    #self.preferred_amount * content_items.sum { |item| item.quantity }
  end
end

spree_customized/app/models/spree/jne/price.rb
module Spree
  module Jne
    class Price < ActiveRecord::Base
      require 'roo'

      self.table_name = "spree_jne_prices"
      belongs_to :shipping, class_name: Spree::Jne::Shipping
      include TenantScoped

    end
  end
end

spree_customized/app/models/spree/jne/shipping.rb
module Spree
  module Jne
    class Shipping < ActiveRecord::Base
      require 'roo'

      self.table_name = "spree_jne_shippings"
      include TenantScoped
      has_one :price, class_name: Spree::Jne::Price, dependent: :destroy
      before_save :set_tenant

      belongs_to :city
      belongs_to :sub_district

      delegate :name, to: :city, prefix: 'city'
      delegate :name, to: :sub_district, prefix: 'district'
      delegate_belongs_to :price, :reg_price, :reg_estimation, :oke_price, :oke_estimation, :yes_price, :yes_estimation

      scope :yes, -> {where(jne_type: 'yes')}
      scope :ss, -> {where(jne_type: 'oke')}
      scope :reg, -> {where(jne_type: 'reg')}

      accepts_nested_attributes_for :price
      
      def self.jne_type
        [["Express", "yes"], ["OKE", "oke"], ["Reguler", "reg"]]
      end

      def self.search(params)
        conditions = []
        
        conditions << "city_id = '#{params[:ct]}'" if params[:ct].present?

        if conditions.any?
          where(conditions.join(" AND "))
        else
          scoped
        end
      end

      def set_tenant
        self.tenant_id = tenant.id if tenant
      end

      def self.upload_file(file, jtype)
        file_data = process_upload(file)
        return {error: true, message: file_data[:message]} if file_data[:error]
        #path = "#{Rails.root}/public/spree/sample_shippings/jne.xls"
        path = file_data[:path]
        delay(queue: 'shippings').open_spreadsheet(path, Multitenant.current_tenant.id)
        {error: false, message: "Successfully to upload, data will importing in the background"}
      end

      def self.process_upload(file)
        return {error: true, message: "Please select file."} if file.nil?
        if [".xls", ".xlsx"].include?(File.extname(file.original_filename))
          uploading = save_file file
          #prosess upload
          {error: false, message: 'Successfully Upload, data will importing in the background'}.merge(uploading)
        else
          {error: true, message: "Invalid Format Type of file."}
        end
      end

      def self.get_price(package, jtype)
        address = package.contents.first.line_item.order.ship_address rescue nil
        if address        
          #find level district
          jne = joins(:price).where(city_id: address.city_id, sub_district_id: address.sub_district_id).first 
          return eval "jne.#{jtype}_price" if jne

          #find level district
          jne = joins(:price).where(sub_district_id: address.sub_district_id).first 
          return eval "jne.#{jtype}_price" if jne

          #find level city
          jne = joins(:price).where(city_id: address.city_id).first 
          return eval "jne.#{jtype}_price" if jne
        end
      end

      def self.open_spreadsheet(path, tenant_id=nil)
        spreadsheet = case File.extname(path)
          when ".xls" then Roo::Excel.new(path, nil, :ignore)
          when ".xlsx" then Roo::Excelx.new(path, nil, :ignore)
        end
        header = spreadsheet.row(1)
        state_name = ""
        city_name  = ""
        hash = []
        tenant = tenant_id
        country = Spree::Country.where("tenant_id = ? and (lower(iso) =? or lower(iso_name) =?)", tenant_id, "id", "id").first
        header = ["Kota / Kabupaten", "Kecamatan", "REGULER", nil, "OKE", nil, "YES"]
        Spree::Jne::Shipping.where(tenant_id: tenant).delete_all
        Spree::Jne::Price.where(tenant_id: tenant).delete_all
        if header != spreadsheet.first
          return false
        end  
        spreadsheet.each_with_index do |row, index|
          next if index < 2
          city_name  = row[0] if row[0].present?
          district_name  = row[1] if row[1].present?
          reg_price      = row[2] if row[2].present?
          reg_estimation = row[3] if row[3].present?
          oke_price = row[4] if row[4].present?
          oke_estimation = row[5] if row[5].present?
          yes_price = row[6] if row[6].present?
          yes_estimation = '1'
          
          city = Spree::City.where(country_id: country.id, name: city_name, code_name: city_name, tenant_id: tenant_id).first_or_initialize
          district = city.sub_districts.where(name: district_name, code_name: district_name, tenant_id: tenant_id).first_or_initialize
          if city.save && district.save
            shippings = Spree::Jne::Shipping.new()
            hash << {city_id: city.id, sub_district_id: district.id, tenant_id: tenant, price_attributes: {reg_price: reg_price, reg_estimation: reg_estimation, oke_price: oke_price, oke_estimation: oke_estimation, yes_price: yes_price, yes_estimation: yes_estimation, tenant_id: tenant}}
          end
        end
        Spree::Jne::Shipping.create hash
        #File.delete(path) if File.exist?(path)
      end

      def self.save_file upload
        file_name = upload.original_filename if upload != ''
        file = upload.read    

        file_type = file_name.split('.').last
        new_name_file = "shippings-#{Time.now.to_i}"
        new_file_name_with_type = "#{new_name_file}." + file_type
        upload_path = "#{Rails.root.to_s}/public/spree/shippings"

        #create directory if path not found
        unless Dir.exists?(upload_path)
          dirs = upload_path.split("/")
          tmp_dir = []
          dirs.each do |dir|
            tmp_dir << dir
            next if tmp_dir.join("/") == ""
            path = tmp_dir.join("/")
            puts path.inspect
            unless Dir.exists?(path)
              Dir.mkdir(path)
            end
          end
        end
        path_of_filename = upload_path + "/" + new_file_name_with_type
        File.open(path_of_filename, "wb")  do |f|  
          f.write(file) 
        end

        {path: path_of_filename, name: new_file_name_with_type}
      end

      def self.collecting_data
        tenant = Spree::Tenant.find_by_code("salihara")
        country = Spree::Country.where(name: "Indonesia", tenant_id: tenant.id).first
        shippings =  Spree::Jne::Shipping.where(tenant_id: tenant.id).order(:state_name).group_by{|x| x.state_name}
        state = {}
        shippings.each do |key, val|
          state["#{key}"] = {}
          val.group_by{|x| x.city_name}.each do |k, v|
            state["#{key}"]["#{k}"] = {}
            state["#{key}"]["#{k}"] = v.group_by{|x| x.district_name}.map{|x| x.first}
          end
        end
        Spree::State.where(country_id: country.id, tenant_id: tenant.id).destroy_all
        state.each do |key, val|
          state = Spree::State.new(name: key, tenant_id: tenant.id, country_id: country.id)
          state.save
          val.each do |city, districts|
            city = state.cities.new(tenant_id: tenant.id, country_id: country.id, name: city, code_name: city)
            city.save
            districts.each do |district|
              dis = city.sub_districts.build(tenant_id: tenant.id, name: district, code_name: district)
              dis.save
            end
          end
        end
        puts "done"
      end
    end
  end
end

spree_customized/app/controllers/spree/admin/jne/shippings_controller.rb
module Spree
  module Admin
    module Jne
      class ShippingsController < Spree::Admin::BaseController
        before_action :define_jne_shipping, only: [:edit, :update, :show, :destroy]
        helper_method :collection_url

        def index
          @jne_shippings = Spree::Jne::Shipping.search(params).page(params[:page]).per(10)
        end

        def new
          @jne_shipping = Spree::Jne::Shipping.new
        end

        def create
          @jne_shipping = Spree::Jne::Shipping.new(params_jne_shipping.merge(tenant_id: Multitenant.current_tenant.id))
          if @jne_shipping.save
            flash[:success] = flash_message_for(@jne_shipping, :successfully_created)
            redirect_to admin_jne_shippings_path
          else
            render :new
          end
        end

        def edit
        end

        def update
          if @jne_shipping.update_attributes(params_jne_shipping)
            flash[:success] = flash_message_for(@jne_shipping, :successfully_updated)
            redirect_to admin_jne_shippings_path
          else
            render :new
          end
        end

        def destroy
          @jne_shipping.destroy
        end

        def show

        end

        def upload
          if params[:upload_data] != nil
            uploaded = Spree::Jne::Shipping.upload_file(params[:upload_data], params[:jne_type])
            redirect_to admin_jne_shippings_path, notice: uploaded[:message]
          else
            flash[:error] = "Select file for Upload"
            redirect_to admin_jne_shippings_path
          end
        end

        def collection_search_base
          data = Spree::Jne::Shipping.search(params)
          @states   = data.collect(&:state_name).uniq
          @cities   = data.collect(&:city_name).uniq
          @district = data.collect(&:district_name).uniq
          render json: {states: @states, cities: @cities, districts: @district}
        end

        private
        def collection_url(options = {})
          spree.polymorphic_url([:admin, model_class], options)
        end

        def define_jne_shipping
          @jne_shipping = Spree::Jne::Shipping.find(params[:id])
        end

        def params_jne_shipping
          params.require(:jne_shipping).permit(:state_name, :city_name, :district_name, :code_name, :jne_type)
        end

        def check_access
          unless try_spree_current_user.try(:as_superadmin?)
            flash[:error] = 'Authorization Failure'
            redirect_to admin_jne_shippings_path and return
          end
        end
      end
    end
  end
end

spree_customized/app/views/spree/admin/jne/shippings/_form.html.erb
<div data-hook="admin_product_form_fields">  
  <div class="left eighteen columns alpha" data-hook="admin_product_form_left">    
    <%= f.field_container :city_id do %>
      <%= f.label :city_id, "City" %>
      <%= f.select :city_id, options_for_select(Spree::City.where(country_id: Spree::Country.find_by_iso('ID').try(:id)).order(:name).map{|x| [x.name, x.id]}, selected: f.object.city_id), {}, class: "fullwidth select2" %>
      <%= f.error_message_on :city_id %>
    <% end %>

    <%= f.field_container :sub_district_id do %>
      <%= f.label :sub_district_id, "District" %>
      <%= f.select :sub_district_id, options_for_select(Spree::SubDistrict.order(:name).map{|x| [x.name, x.id]}, selected: f.object.sub_district_id),{}, class: "fullwidth select2" %>
      <%= f.error_message_on :city_id %>
    <% end %>

    <%- %w(reg oke yes).each do |t| %>
      <%= f.field_container "#{t}_price".to_sym do %>
        <%= f.label "#{t}_price".to_sym, "#{t.titleize} Price" %>
        <%= f.text_field "#{t}_price".to_sym, :class => 'fullwidth' %>
        <%= f.error_message_on "#{t}_price".to_sym %>
      <% end %>

      <%= f.field_container "#{t}_estimation".to_sym do %>
        <%= f.label "#{t}_estimation".to_sym, "#{t} Estimation" %>
        <%= f.text_field "#{t}_estimation".to_sym, :class => 'fullwidth' %>
        <%= f.error_message_on "#{t}_estimation".to_sym %>
      <% end %>
    <% end %>
  </div>
</div>

spree_customized/app/views/spree/admin/jne/shippings/destroy.js.erb
$(".state-<%= @jne_shipping.id %>").remove()

spree_customized/app/views/spree/admin/jne/shippings/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:edit_jne_shipping) %>
<% end %>

<!--<#%= render :partial => 'spree/shared/error_messages', :locals => { :target => @page } %>-->

<%= form_for [:admin, @jne_shipping], :method => :put, :html => { :multipart => true } do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div class="clear"></div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <button class="fa fa-refresh button" name="button" type="submit">Update</button>
      <span class="or">or</span>
      <a class="button fa fa-remove" href="http://salihara.local:3000/admin/jne/shippings" icon="remove">Cancel</a>
    </div>
  </fieldset>
<% end %>

spree_customized/app/views/spree/admin/jne/shippings/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_jne_shippings) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new), new_admin_jne_shipping_url, :icon => 'plus', :id => 'admin_new_shipping' %>
  </li>
<% end if can? :edit, Spree::Page.new %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:filter) %>
<% end %>

<% content_for :table_filter do %>
  <div class="alpha eight columns" data-hook="admin_product_reviews_sidebar">
    <%= form_tag upload_admin_jne_shippings_path, multipart: true do |f| %>
        <div data-hook="admin_product_reviews_index_search">
          <div class="alpha nine columns">
            <div class="field">
              <%= label_tag :upload_data, "Upload Data Jne Terbaru" %>
              <%= file_field_tag :upload_data %>
            </div>
          </div>
          <div class="alpa nine columns">
            <p>
               Download sample data</br>
               <a href="/spree/sample_shippings/jne.xls">Jne XLS</a>
            </p>
          </div>
        </div>
        <div data-hook="admin_product_reviews_index_search">
          <div class="alpha nine columns">
<!--             <div class="field">
              <#%= label_tag :jne_type, Spree.t('jne_type') %>
              <#%= select_tag :jne_type, options_for_select(Spree::Jne::Shipping.jne_type) %>
            </div>
 -->          </div>
        </div>
        <div class="clear"></div>
        <div class="form-buttons actions filter-actions" data-hook="admin_products_index_search_buttons">
          <%= button Spree.t(:submit), 'submit' %>
        </div>
    <% end %>
  </div>
  <div class="alpha eight column" data-hook="admin_product_reviews_sidebar">
    <%= form_tag admin_jne_shippings_path, multipart: true, method: :get do |f| %>
        <div data-hook="admin_product_reviews_index_search">
          <div class="alpha six columns">
            <div class="field">
              <label>City</label>
              <%= select_tag :ct, options_for_select(Spree::City.order(:name).map{|x| [x.name, x.id]}, selected: params[:ct]), class: 'select2' %>
            </div>
          </div>
        </div>
        <div class="clear"></div>
        <br>
        <div class="form-buttons actions filter-actions" data-hook="admin_products_index_search_buttons">
          <%= button Spree.t(:search), 'search' %>
        </div>
    <% end %>
  </div>
<% end %>

<%= paginate @jne_shippings %>

<% if @jne_shippings.any? %>
  <table class="index responsive" id="listing_jne_shippings" data-hook>
<!--     <colgroup>
       <col style="width: 10%;">
       <col style="width: 10%;">
       <col style="width: 10%;">
       <col style="width: 10%;">
    </colgroup> -->
    <thead>
      <tr data-hook="admin_jne_shippings_index_headers">
        <th rowspan="2"><%= Spree.t("cities") %></th>
        <th rowspan="2"><%= Spree.t('sub_districts') %></th>
        <th colspan="2">Reguler</th>
        <th colspan="2">Oke</th>
        <th colspan="2">YES</th>
        <th data-hook="admin_jne_shippings_index_header_actions" class="actions"></th>
      </tr>
      <tr data-hook="admin_jne_shippings_index_headers">
        <th>Tarif</th>
        <th>ETD</th>
        <th>Tarif</th>
        <th>ETD</th>
        <th>Tarif</th>
        <th>ETD</th>
        <th data-hook="admin_jne_shippings_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @jne_shippings.each do |page| %>
      <tr data-hook="admin_jne_shippings_index_rows" class="state-<%= page.id %> <%= cycle('odd', 'even') %>">
        <td class="align-center"><%= page.city_name rescue ''%></td>
        <td class="align-center"><%= page.district_name rescue '' %></td>
        <td class="align-center"><%= Spree::Money.new(page.reg_price, { currency: Spree::Config[:currency] }) %></td>
        <td class="align-center"><%= page.reg_estimation %></td>
        <td class="align-center"><%= Spree::Money.new(page.oke_price, { currency: Spree::Config[:currency] }) %></td>
        <td class="align-center"><%= page.oke_estimation %></td>
        <td class="align-center"><%= Spree::Money.new(page.yes_price, { currency: Spree::Config[:currency] }) %></td>
        <td class="align-center"><%= page.yes_estimation %></td>
        <td class='actions align-center' data-hook="admin_jne_shippings_index_row_actions">
          <%= link_to_edit_url edit_admin_jne_shipping_path(page), :title => "admin_edit_#{dom_id(page)}", :no_text => true %>
          <%= link_to_delete page, url: admin_jne_shipping_path(page), :no_text => true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/order')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_jne_shipping_path %>!
  </div>
<% end %>

<%= paginate @jne_shippings %>

spree_customized/app/views/spree/admin/jne/shippings/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_jne_shipping) %>
<% end %>

<!--<#%= render :partial => 'spree/shared/error_messages', :locals => { :target => @jne_shipping } %>-->

<%= form_for [:admin, @jne_shipping], :html => { :multipart => true } do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div class="clear"></div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <button class="fa fa-refresh button" name="button" type="submit">Save</button>
      <span class="or">or</span>
      <a class="button fa fa-remove" href="http://salihara.local:3000/admin/jne/shippings" icon="remove">Cancel</a>
    </div>
  </fieldset>
<% end %>