spree_customized/config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do

    get "mail_methods/email_users/send" => "mail_methods#email_users", as: :email_users
    post "mail_methods/post_email_users/send" => "mail_methods#post_email_users", as: :post_email_users
    resources :tenants
    resources :sliders
    resources :socials
    resources :promo_banners

    resources :users do
      get :send_email_notification
    end
    resources :donations, only: [:index]

    namespace :jne do
      resources :shippings do
        collection { post :upload }
        collection { get :collection_search_base}
      end
    end
    resources :menu, only: [:index, :create]
    resources :pages
    resources :product_reviews, only: [:index, :edit, :update, :destroy] do
      put :update_status
    end
    resources :states do
      resources :cities
    end

    resources :cities, only: [:index] do
      resources :sub_districts
    end

    resources :sub_districts, only: [:index]

    resources :products do
      collection { post :upload_file}
    end

    resources :taxons

    # resources :users do
    #   # collection do
    #   #   get :index_customer
    #   #   post :create_customer
    #   #   get :new_customer
    #   #   get 'edit_customer/:id/edit', :as => :edit_customer, :action => 'edit_customer'
    #   #   put 'update_customer/:id', :as => :update_customer, :action => 'update_customer'
    #   #   delete 'destroy_customer/:id', :as => :destroy_customer, :action => 'destroy_customer'
    #   # end
    # end

    resources :roles
    resources :features
    resources :home
    resources :users_customers
    resources :reports_customers
    resources :activity_logs do
      collection { get 'show_by_date/:date', :as => :show_by_date, :action => 'show_by_date'}
    end
  end

  resources :pages, only: [:show]
  resources :translations, only: [:show]

  namespace :api, defaults: { format: 'json' } do
  	resources :tenants
    resources :cities, only:[:index, :show]
    resources :sub_districts, only:[:index, :show]

    namespace :nontenant, defaults: { format: 'json' } do
      resources :products, only:[:index, :show]
      resources :users
      get "check_email_exist" => "users#check_email_exist", as: :check_user
      get "get_single_payment_method" => "general#get_single_payment_method", as: :get_single_payment_method
      get "get_single_shipping_method" => "general#get_single_shipping_method", as: :get_single_shipping_method
      get "get_single_shipping_rate" => "general#get_single_shipping_rate", as: :get_single_shipping_rate
      get "get_single_shipping_rate_by_tenant" => "general#get_single_shipping_rate_by_tenant", as: :get_single_shipping_rate_by_tenant
      post "custom_order" => "general#custom_order", as: :custom_order

      concern :order_routes do
        member do
          put :cancel
          put :empty
          put :apply_coupon_code
        end

        resources :line_items
        resources :payments do
          member do
            put :authorize
            put :capture
            put :purchase
            put :void
            put :credit
          end
        end

        resources :shipments, only: [:create, :update] do
          member do
            put :ready
            put :ship
            put :add
            put :remove
          end
        end

        resources :addresses, only: [:show, :update]

        resources :return_authorizations do
          member do
            put :add
            put :cancel
            put :receive
          end
        end
      end

      resources :checkouts, only: [:update], concerns: :order_routes do
        member do
          put :next
          put :advance
        end
      end
      get '/orders/mine', to: 'orders#mine', as: 'my_orders'
      get "/orders/current", to: "orders#current", as: "current_order"
      resources :orders, concerns: :order_routes
      resources :shipments, only: [:create, :update] do
        member do
          put :ready
          put :ship
          put :add
          put :remove
        end
      end
    end

    devise_for :spree_user,
               :class_name => 'Spree::User',
               :controllers => { :sessions => 'spree/api/user_sessions', :passwords => 'spree/api/user_passwords'},
               :skip => [:unlocks, :omniauth_callbacks, :registrations],
               :path_prefix => :api,
               :path => :user
  end

  post 'cart' => "orders#edit", as: :cart_path_post
  get "account/orders" => "users#orders", as: :account_orders
  get "account/addresses" => "users#addresses", as: :account_addresses
  get "account/configuration" => "users#configuration", as: :account_configuration

  resources :products do
    collection do
      get "categories/:category_name" => "products#index", as: :products_category
    end
  end

  devise_scope :spree_user do
    get '/confirmation/:token' => 'user_registrations#confirmation', :as => :confirmation
  end

  get "states_by_country" => "info_addresses#states_by_country", as: :states_by_country
  get "cities_by_country" => "info_addresses#cities_by_country", as: :cities_by_country
  get "cities_by_state" => "info_addresses#cities_by_state", as: :cities_by_state
  get "sub_districts_by_city" => "info_addresses#sub_districts_by_city", as: :sub_districts_by_city
  get "be-a-member/:package_type" => "users#be_a_member", as: :be_a_member
  get "be-a-member/completed/:transaction_no" => "users#be_a_member_completed", as: :be_a_member_completed
  post "submit_be_a_member" => "users#submit_be_a_member", as: :submit_be_a_member
  patch "submit_be_a_member" => "users#submit_be_a_member", as: :submit_be_a_member_update

  resources :product_reviews, only: [:create]
  resources :orders do
    collection do
      post :donation
    end
  end
  resources :donations, only: [:index, :create, :show]
end

spree_customized/app/controllers/spree/admin/cities_controller.rb
class Spree::Admin::CitiesController < Spree::Admin::BaseController
  helper_method :collection_url
  before_action :define_state
  before_action :define_states
  before_action :define_city, only: [:edit, :update, :destroy]

  def index
    @cities = @state.cities.order(:name)
    respond_to do |f|
      f.html
      f.js {render partial: 'city_list'}
    end
  end

  def new
    @city = Spree::City.new(state_id: @state.id, country_id: @state.country.id)
  end
  
  def create
    @city = Spree::City.new(params_page.merge(tenant_id: Multitenant.current_tenant.id))
    if @city.save
      flash[:success] = flash_message_for(@city, :successfully_created)
      redirect_to admin_state_cities_path(params[:state_id])
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @city.update_attributes(params_page)
      flash[:success] = flash_message_for(@city, :successfully_created)
      redirect_to admin_state_cities_path(params[:state_id])
    else
      render :edit
    end
  end

  def destroy
    @city.destroy
  end

  private
    def collection_url(options = {})
      spree.polymorphic_url([:admin, model_class], options)
    end

    def define_city
      @city = Spree::City.find_by_id(params[:id])
      flash[:error] = "City not found" unless @city
      redirect_to admin_state_cities_path(@state) and return unless @city
    end
 
    def define_state
      @state = Spree::State.find_by_id params[:state_id]
    end

    def define_states
      @states = Spree::State.order(:name)
    end

    def params_page
      params.require(:city).permit(:name, :code_name, :state_id, :country_id, :tenant_id)
    end
end

spree_customized/app/controllers/spree/api/cities_controller.rb
class Spree::Api::CitiesController < Spree::Api::BaseController
  skip_before_filter :check_for_user_or_api_key
  skip_before_filter :authenticate_user

  def index
    @cities = Spree::City.accessible_by(current_ability, :read).ransack(params[:q]).result.
    includes(:state).order('name ASC').
    page(params[:page]).per(params[:per_page])
    city = Spree::City.order("updated_at ASC").last
    if stale?(city)
      respond_with(@cities)
    end
  end

  def show
    @city = Spree::City.accessible_by(current_ability, :read).find(params[:id])
    respond_with(@city)
  end
end

spree_customized/app/views/spree/admin/cities/_city_list.html.erb
<div id="new_state" data-hook></div>

<table class="index" id='listing_states' data-hook>
  <colgroup>
    <col style="width: 70%" />
    <col style="width: 15%" />
    <col style="width: 15%" />
  </colgroup>
  <thead>
    <tr data-hook="states_header">
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:name_code) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @cities.each do |city| %>
      <tr id="<%= spree_dom_id city %>" data-hook="states_row" class="<%= cycle('odd', 'even')%>">
        <td><%= city.name %></td>
        <td class="align-center"><%= city.code_name %></td>
        <td class="actions">
          <%= link_to_with_icon 'edit', Spree.t(:edit), edit_admin_state_city_url(@state, city), :no_text => true %>
          <%= link_to_delete city, url: admin_state_city_path(@state, city), :no_text => true %>
        </td>
      </tr>
    <% end %>
    <% if @cities.empty? %>
      <tr><td colspan="3"><%= Spree.t(:none) %></td></tr>
    <% end %>
  </tbody>
</table>

spree_customized/app/views/spree/admin/cities/_form.html.erb
<div data-hook="admin_state_form_fields" class="row">
  <div class="alpha six columns">
    <%= f.field_container :name do %>
      <%= f.label :name, Spree.t(:name) %>
      <%= f.text_field :name, :class => 'fullwidth' %>
    <% end %>
  </div>
  <div class="omega six columns">
    <%= f.field_container :abbr do %>
      <%= f.label :code_name, Spree.t(:code_name) %>
      <%= f.text_field :code_name, :class => 'fullwidth' %>
      <%= f.hidden_field :state_id %>
      <%= f.hidden_field :country_id %>
    <% end %>
  </div>
</div>

spree_customized/app/views/spree/admin/cities/destroy.js.erb
$("#spree_city_<%= @city.id %>").remove();

spree_customized/app/views/spree/admin/cities/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_city) %> <i class="fa fa-arrow-right"></i> <%= @city.name %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_cities_list), spree.admin_state_cities_url(@state), :icon => 'arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @city } %>

<%= form_for [:admin, @state, @city] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'refresh' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_state_cities_path(@state), :class => 'button' %>
    </div>
  </fieldset>
<% end %>

spree_customized/app/views/spree/admin/cities/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:cities) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_state_link">
    <%= button_link_to Spree.t(:new_city), new_admin_state_city_url(@state), { :remote => true, :icon => 'plus', :id => 'new_state_link' } %>
  </li>
<% end %>

<div data-hook="country" class="field row">
  <%= label_tag :state, Spree.t(:state) %>
  <select id="state" class='observe_field select2 fullwidth' data-base-url="<%=admin_cities_path(:format => :js) %>?state_id=" data-update="#city-list">
  <%= options_from_collection_for_select(@states, :id, :name, @state.id) %>
  </select>
</div>

<%= image_tag 'select2-spinner.gif', :plugin => 'spree', :style => 'display:none;', :id => 'busy_indicator' %>

<div id="city-list" data-hook>
  <%= render :partial => 'city_list'%>
</div>
<script type="text/javascript">
  $(document).ready(function () {
    'use strict';
    $('#state').on('change', function () {
      var new_state_link_href = $('#new_state_link a').prop('href');
      var selected_country_id = $('#state option:selected').prop('value');
      var new_link = new_state_link_href.replace(/states\/(\d+)/,
        'states/' + selected_country_id);
      $('#new_state_link a').attr('href', new_link);
    });
  });
</script>

spree_customized/app/views/spree/admin/cities/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @city } %>

<% content_for :page_title do %>
  <%= Spree.t(:new_city) %>
<% end %>

<%= form_for [:admin, @state, @city] do |f| %>
  <fieldset>
    <legend><%= Spree.t(:new_state) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'ok' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_state_cities_path(@state), :class => 'button' %>
    </div>
  </fieldset>
<% end %>

spree_customized/app/views/spree/admin/cities/new.js.erb
$("#new_state").html("<%= escape_javascript(render :template => 'spree/admin/cities/new', :formats => [:html], :handlers => [:erb]) %>");
$("#new_state_link").parent().hide();