spree_customized/config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do

    get "mail_methods/email_users/send" => "mail_methods#email_users", as: :email_users
    post "mail_methods/post_email_users/send" => "mail_methods#post_email_users", as: :post_email_users
    resources :tenants
    resources :sliders
    resources :socials
    resources :promo_banners

    resources :users do
      get :send_email_notification
    end
    resources :donations, only: [:index]

    namespace :jne do
      resources :shippings do
        collection { post :upload }
        collection { get :collection_search_base}
      end
    end
    resources :menu, only: [:index, :create]
    resources :pages
    resources :product_reviews, only: [:index, :edit, :update, :destroy] do
      put :update_status
    end
    resources :states do
      resources :cities
    end

    resources :cities, only: [:index] do
      resources :sub_districts
    end

    resources :sub_districts, only: [:index]

    resources :products do
      collection { post :upload_file}
    end

    resources :taxons

    # resources :users do
    #   # collection do
    #   #   get :index_customer
    #   #   post :create_customer
    #   #   get :new_customer
    #   #   get 'edit_customer/:id/edit', :as => :edit_customer, :action => 'edit_customer'
    #   #   put 'update_customer/:id', :as => :update_customer, :action => 'update_customer'
    #   #   delete 'destroy_customer/:id', :as => :destroy_customer, :action => 'destroy_customer'
    #   # end
    # end

    resources :roles
    resources :features
    resources :home
    resources :users_customers
    resources :reports_customers
    resources :activity_logs do
      collection { get 'show_by_date/:date', :as => :show_by_date, :action => 'show_by_date'}
    end
  end

  resources :pages, only: [:show]
  resources :translations, only: [:show]

  namespace :api, defaults: { format: 'json' } do
  	resources :tenants
    resources :cities, only:[:index, :show]
    resources :sub_districts, only:[:index, :show]

    namespace :nontenant, defaults: { format: 'json' } do
      resources :products, only:[:index, :show]
      resources :users
      get "check_email_exist" => "users#check_email_exist", as: :check_user
      get "get_single_payment_method" => "general#get_single_payment_method", as: :get_single_payment_method
      get "get_single_shipping_method" => "general#get_single_shipping_method", as: :get_single_shipping_method
      get "get_single_shipping_rate" => "general#get_single_shipping_rate", as: :get_single_shipping_rate
      get "get_single_shipping_rate_by_tenant" => "general#get_single_shipping_rate_by_tenant", as: :get_single_shipping_rate_by_tenant
      post "custom_order" => "general#custom_order", as: :custom_order

      concern :order_routes do
        member do
          put :cancel
          put :empty
          put :apply_coupon_code
        end

        resources :line_items
        resources :payments do
          member do
            put :authorize
            put :capture
            put :purchase
            put :void
            put :credit
          end
        end

        resources :shipments, only: [:create, :update] do
          member do
            put :ready
            put :ship
            put :add
            put :remove
          end
        end

        resources :addresses, only: [:show, :update]

        resources :return_authorizations do
          member do
            put :add
            put :cancel
            put :receive
          end
        end
      end

      resources :checkouts, only: [:update], concerns: :order_routes do
        member do
          put :next
          put :advance
        end
      end
      get '/orders/mine', to: 'orders#mine', as: 'my_orders'
      get "/orders/current", to: "orders#current", as: "current_order"
      resources :orders, concerns: :order_routes
      resources :shipments, only: [:create, :update] do
        member do
          put :ready
          put :ship
          put :add
          put :remove
        end
      end
    end

    devise_for :spree_user,
               :class_name => 'Spree::User',
               :controllers => { :sessions => 'spree/api/user_sessions', :passwords => 'spree/api/user_passwords'},
               :skip => [:unlocks, :omniauth_callbacks, :registrations],
               :path_prefix => :api,
               :path => :user
  end

  post 'cart' => "orders#edit", as: :cart_path_post
  get "account/orders" => "users#orders", as: :account_orders
  get "account/addresses" => "users#addresses", as: :account_addresses
  get "account/configuration" => "users#configuration", as: :account_configuration

  resources :products do
    collection do
      get "categories/:category_name" => "products#index", as: :products_category
    end
  end

  devise_scope :spree_user do
    get '/confirmation/:token' => 'user_registrations#confirmation', :as => :confirmation
  end

  get "states_by_country" => "info_addresses#states_by_country", as: :states_by_country
  get "cities_by_country" => "info_addresses#cities_by_country", as: :cities_by_country
  get "cities_by_state" => "info_addresses#cities_by_state", as: :cities_by_state
  get "sub_districts_by_city" => "info_addresses#sub_districts_by_city", as: :sub_districts_by_city
  get "be-a-member/:package_type" => "users#be_a_member", as: :be_a_member
  get "be-a-member/completed/:transaction_no" => "users#be_a_member_completed", as: :be_a_member_completed
  post "submit_be_a_member" => "users#submit_be_a_member", as: :submit_be_a_member
  patch "submit_be_a_member" => "users#submit_be_a_member", as: :submit_be_a_member_update

  resources :product_reviews, only: [:create]
  resources :orders do
    collection do
      post :donation
    end
  end
  resources :donations, only: [:index, :create, :show]
end

spree_customized/app/views/spree/admin/pages/_form.html.erb
<div data-hook="admin_product_form_fields">
  
  <div class="left eighteen columns alpha" data-hook="admin_product_form_left">    
    <%= f.field_container :title do %>
      <%= f.label :title, raw(Spree.t(:title) + content_tag(:span, ' *', :class => 'required')) %>
      <%= f.text_field :title, :class => 'fullwidth' %>
      <%= f.error_message_on :title %>
    <% end %>
    <%= f.field_container :meta_title do %>
      <%= f.label :meta_title, raw(Spree.t(:meta_title)) %>
      <%= f.text_field :meta_title, :class => 'fullwidth' %>
      <%= f.error_message_on :title %>
    <% end %>
    <%= f.field_container :meta_description do %>
      <%= f.label :meta_description, raw(Spree.t(:meta_description)) %>
      <%= f.text_field :meta_description, :class => 'fullwidth' %>
      <%= f.error_message_on :meta_description %>
    <% end %>

    <%= f.field_container :content do %>
      <%= f.label :content, Spree.t(:content) %>
      <%= f.text_area :content, {:rows => 20, :class => 'fullwidth'} %>
      <%= f.error_message_on :content %>
    <% end %>
  </div>
</div>

spree_customized/app/views/spree/admin/pages/destroy.js.erb
$(".state-<%= @page.friendly_id %>").remove()

spree_customized/app/views/spree/admin/pages/edit.html.erb
<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:'i18n.translations'), spree.admin_translations_path('pages', @page.id), :icon => 'flag' %>
  </li>
<% end %>

<% content_for :page_title do %>
  <%= Spree.t(:edit_page) %>
<% end %>

<!--<#%= render :partial => 'spree/shared/error_messages', :locals => { :target => @page } %>-->

<%= form_for [:admin, @page], :method => :put, :html => { :multipart => true } do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div class="clear"></div>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

spree_customized/app/views/spree/admin/pages/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_pages) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_page), new_admin_page_url, :icon => 'plus', :id => 'admin_new_page' %>
  </li>
<% end if can? :edit, Spree::Page.new %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<%= paginate @pages %>

<% if @pages.any? %>
  <table class="index responsive" id="listing_pages" data-hook>
    <colgroup>
       <col style="width: 70%;">
       <col style="width: 10%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_pages_index_headers">
        <th>Title</th>
        <th data-hook="admin_pages_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @pages.each do |page| %>
      <tr data-hook="admin_pages_index_rows" class="state-<%= page.friendly_id %> <%= cycle('odd', 'even') %>">
        <td class="align-center"><%= page.title %></td>
        <td class='actions align-center' data-hook="admin_pages_index_row_actions">
          <%= link_to_edit_url edit_admin_page_path(page), :title => "admin_edit_#{dom_id(page)}", :no_text => true %>
          <%= link_to_delete page, url: admin_page_path(page), :no_text => true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/order')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_page_path %>!
  </div>
<% end %>

<%= paginate @pages %>

spree_customized/app/views/spree/admin/pages/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_page) %>
<% end %>

<!--<#%= render :partial => 'spree/shared/error_messages', :locals => { :target => @page } %>-->

<%= form_for [:admin, @page], :html => { :multipart => true } do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div class="clear"></div>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>